"""Source-specific export of processed TTC cornering sweeps to force-demand branches.

The first supported route is the WUFR-26 ``Cornering Trojan`` convention produced by
``April_Interpolator.m``.  The Trojan file is already a processed/smoothed source: this
module does not refit, smooth, extrapolate, or evaluate Magic Formula.  It selects an
explicit operating point from the stored channels, chooses one documented physical
slip/force quadrant, truncates at the first source peak, and requires the resulting
pre-peak magnitude branch to be monotonic before it can enter the generic force-demand
contract.

This separation is deliberate.  Raw TTC filtering and the team's TyDex parser use
other tolerances/convention adapters; those routes must receive their own named export
profiles rather than being silently combined here.
"""

from __future__ import annotations

from dataclasses import dataclass
import math
from pathlib import Path
from typing import Mapping

from .force_demand import (
    LateralForceBranch,
    LateralForceCurveSample,
    TireLateralForceBranchSet,
)
from .io import load_mat_ttc_channels
from .lateral import TireDataError, TireOperatingPoint


REQUIRED_CORNERING_CHANNELS = ("FZ", "SL", "SA", "P", "IA", "FY", "V")


@dataclass(frozen=True)
class TtcCorneringTrojanProfile:
    """Reviewed interpretation of one already-processed cornering Trojan source."""

    profile_id: str
    source_description: str
    source_fz_is_positive_magnitude: bool = True
    operating_point_tolerance: float = 1.0e-6
    slip_ratio_tolerance: float = 1.0e-12
    speed_target_kph: float = 40.2
    speed_tolerance_kph: float = 1.0e-6
    selected_slip_sign: int = -1
    selected_force_sign: int = 1
    monotonic_force_tolerance_n: float = 1.0e-6

    def __post_init__(self) -> None:
        if not self.profile_id or not self.source_description:
            raise TireDataError("TTC cornering profile identity and source description are required")
        if self.selected_slip_sign not in (-1, 1) or self.selected_force_sign not in (-1, 1):
            raise TireDataError("selected slip/force signs must be +1 or -1")
        numeric = (
            self.operating_point_tolerance,
            self.slip_ratio_tolerance,
            self.speed_target_kph,
            self.speed_tolerance_kph,
            self.monotonic_force_tolerance_n,
        )
        if not all(math.isfinite(value) for value in numeric):
            raise TireDataError("TTC cornering profile numeric values must be finite")
        if min(
            self.operating_point_tolerance,
            self.slip_ratio_tolerance,
            self.speed_tolerance_kph,
            self.monotonic_force_tolerance_n,
        ) < 0.0:
            raise TireDataError("TTC cornering profile tolerances cannot be negative")


WUFR26_APRIL_CORNERING_TROJAN_V0 = TtcCorneringTrojanProfile(
    profile_id="WUFR26_APRIL_CORNERING_TROJAN_V0",
    source_description=(
        "Processed Cornering Trojan generated by April_Interpolator.m: output channels use "
        "positive FZ targets, 100-point SA sweeps from -12 to +12 deg, V=40.2 km/h, and "
        "the source spline result. Select the negative-SA/positive-FY into-turn quadrant."
    ),
)


@dataclass(frozen=True)
class TtcCorneringBranchAudit:
    """Traceable counts and bounds for one exported source branch."""

    profile_id: str
    total_source_rows: int
    operating_point_rows: int
    selected_quadrant_rows: int
    prepeak_rows: int
    source_peak_slip_angle_deg: float
    source_peak_lateral_force_n: float
    minimum_exported_slip_angle_deg: float
    minimum_exported_lateral_force_n: float
    maximum_exported_slip_angle_deg: float
    maximum_exported_lateral_force_n: float


@dataclass(frozen=True)
class TtcCorneringBranchExport:
    branch: LateralForceBranch
    audit: TtcCorneringBranchAudit


def _channel_rows(
    channels: Mapping[str, tuple[float, ...] | list[float]],
) -> tuple[dict[str, tuple[float, ...]], int]:
    missing = [name for name in REQUIRED_CORNERING_CHANNELS if name not in channels]
    if missing:
        raise TireDataError(f"Cornering source is missing required channels: {missing}")

    normalized: dict[str, tuple[float, ...]] = {}
    lengths: set[int] = set()
    for name in REQUIRED_CORNERING_CHANNELS:
        values = tuple(float(value) for value in channels[name])
        if not values:
            raise TireDataError(f"Cornering source channel {name!r} is empty")
        if not all(math.isfinite(value) for value in values):
            raise TireDataError(f"Cornering source channel {name!r} contains nonfinite values")
        normalized[name] = values
        lengths.add(len(values))
    if len(lengths) != 1:
        raise TireDataError("Cornering source channels do not have a common row count")
    return normalized, lengths.pop()


def _matches(value: float, target: float, tolerance: float) -> bool:
    return math.isclose(value, target, rel_tol=0.0, abs_tol=tolerance)


def export_cornering_trojan_branch(
    channels: Mapping[str, tuple[float, ...] | list[float]],
    operating_point: TireOperatingPoint,
    *,
    branch_id: str,
    authority: str,
    source_branch_description: str,
    profile: TtcCorneringTrojanProfile = WUFR26_APRIL_CORNERING_TROJAN_V0,
    provenance: tuple[tuple[str, str], ...] = (),
) -> TtcCorneringBranchExport:
    """Export one exact processed-Trojan operating point without refitting the tire data."""

    rows, total_rows = _channel_rows(channels)
    target_fz = operating_point.normal_load_n
    target_ia = operating_point.inclination_deg
    target_p = operating_point.pressure_kpa

    selected_rows: list[int] = []
    for index in range(total_rows):
        source_fz = rows["FZ"][index]
        if not profile.source_fz_is_positive_magnitude:
            source_fz = abs(source_fz)
        if not _matches(source_fz, target_fz, profile.operating_point_tolerance):
            continue
        if not _matches(rows["IA"][index], target_ia, profile.operating_point_tolerance):
            continue
        if not _matches(rows["P"][index], target_p, profile.operating_point_tolerance):
            continue
        if abs(rows["SL"][index]) > profile.slip_ratio_tolerance:
            continue
        if not _matches(rows["V"][index], profile.speed_target_kph, profile.speed_tolerance_kph):
            continue
        selected_rows.append(index)

    if len(selected_rows) < 2:
        raise TireDataError(
            "Processed cornering source does not contain enough rows at the exact requested "
            f"operating point Fz={target_fz:g} N, IA={target_ia:g} deg, P={target_p:g} kPa"
        )

    quadrant: list[tuple[float, float, float, float]] = []
    for index in selected_rows:
        source_sa = rows["SA"][index]
        source_fy = rows["FY"][index]
        if profile.selected_slip_sign * source_sa < -profile.operating_point_tolerance:
            continue
        if profile.selected_force_sign * source_fy < -profile.monotonic_force_tolerance_n:
            continue
        quadrant.append((abs(source_sa), abs(source_fy), source_sa, source_fy))

    quadrant.sort(key=lambda item: item[0])
    if len(quadrant) < 2:
        raise TireDataError("Selected TTC slip/force quadrant contains fewer than two rows")

    # Repeated slip magnitudes would make the generic branch ambiguous.  Do not average or
    # otherwise alter them here; a reviewed source-processing stage must resolve duplicates.
    for lower, upper in zip(quadrant, quadrant[1:]):
        if upper[0] <= lower[0] + profile.operating_point_tolerance:
            raise TireDataError(
                "Selected processed-Trojan quadrant contains duplicate/non-increasing slip magnitudes"
            )

    peak_index = max(range(len(quadrant)), key=lambda index: quadrant[index][1])
    prepeak = quadrant[: peak_index + 1]
    if len(prepeak) < 2:
        raise TireDataError("Source lateral-force peak occurs at the first selected slip sample")

    for lower, upper in zip(prepeak, prepeak[1:]):
        if upper[1] <= lower[1] + profile.monotonic_force_tolerance_n:
            raise TireDataError(
                "Processed source pre-peak branch is not strictly monotonic in |Fy|; "
                "this exporter will not smooth, envelope, or delete source points automatically"
            )

    samples = tuple(
        LateralForceCurveSample(
            slip_angle_magnitude_deg=slip_magnitude,
            lateral_force_magnitude_n=force_magnitude,
        )
        for slip_magnitude, force_magnitude, _, _ in prepeak
    )
    peak = prepeak[-1]
    branch = LateralForceBranch(
        branch_id=branch_id,
        operating_point=operating_point,
        samples=samples,
        authority=authority,
        source_branch_description=source_branch_description,
        provenance=(
            ("ttc_export_profile_id", profile.profile_id),
            ("source_slip_sign", str(profile.selected_slip_sign)),
            ("source_force_sign", str(profile.selected_force_sign)),
            ("source_speed_kph", f"{profile.speed_target_kph:.17g}"),
            ("source_processing", "already_processed_trojan_no_refit_in_python"),
        )
        + tuple(provenance),
    )
    return TtcCorneringBranchExport(
        branch=branch,
        audit=TtcCorneringBranchAudit(
            profile_id=profile.profile_id,
            total_source_rows=total_rows,
            operating_point_rows=len(selected_rows),
            selected_quadrant_rows=len(quadrant),
            prepeak_rows=len(prepeak),
            source_peak_slip_angle_deg=peak[2],
            source_peak_lateral_force_n=peak[3],
            minimum_exported_slip_angle_deg=samples[0].slip_angle_magnitude_deg,
            minimum_exported_lateral_force_n=samples[0].lateral_force_magnitude_n,
            maximum_exported_slip_angle_deg=samples[-1].slip_angle_magnitude_deg,
            maximum_exported_lateral_force_n=samples[-1].lateral_force_magnitude_n,
        ),
    )


def export_cornering_trojan_mat_branch(
    path: str | Path,
    operating_point: TireOperatingPoint,
    **kwargs: object,
) -> TtcCorneringBranchExport:
    """Optional-SciPy convenience wrapper for a local processed Cornering Trojan MAT file."""

    channels = load_mat_ttc_channels(path, channels=REQUIRED_CORNERING_CHANNELS)
    return export_cornering_trojan_branch(channels, operating_point, **kwargs)


def build_branch_set(
    exports: tuple[TtcCorneringBranchExport, ...],
    *,
    branch_set_id: str,
    version: str,
    source_tire_id: str,
    intended_tire_id: str,
    authority: str,
    source_path: str,
    provenance: tuple[tuple[str, str], ...] = (),
) -> TireLateralForceBranchSet:
    """Collect reviewed exports into the generic PR #30 branch-set contract."""

    if not exports:
        raise TireDataError("At least one TTC cornering branch export is required")
    return TireLateralForceBranchSet(
        branch_set_id=branch_set_id,
        version=version,
        source_tire_id=source_tire_id,
        intended_tire_id=intended_tire_id,
        authority=authority,
        source_path=source_path,
        branches=tuple(item.branch for item in exports),
        provenance=(("exporter", "ttc_cornering_trojan_v0.1.0"),) + tuple(provenance),
    )
